# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from typing import Any, Callable

from jax._array import Array as _Array
from shape_extensions import IntTuple

type _Shape = IntTuple

type Initializer = Callable[..., _Array[Any]]

def constant[Shape: _Shape = []](
    value: Any, dtype: Any = ...
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def uniform[Shape: _Shape = []](
    scale: float = ..., dtype: Any = ...
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def normal[Shape: _Shape = []](
    stddev: float = ..., dtype: Any = ...
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def truncated_normal[Shape: _Shape = []](
    lower: float = ..., upper: float = ..., dtype: Any = ...
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def zeros[Shape: _Shape = []](
    key: Any, shape: Shape, dtype: Any = ..., out_sharding: Any = ...
) -> _Array[Shape]: ...
def ones[Shape: _Shape = []](
    key: Any, shape: Shape, dtype: Any = ..., out_sharding: Any = ...
) -> _Array[Shape]: ...
def glorot_normal[Shape: _Shape = []](
    **kwargs: Any,
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def glorot_uniform[Shape: _Shape = []](
    **kwargs: Any,
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def he_normal[Shape: _Shape = []](
    **kwargs: Any,
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def he_uniform[Shape: _Shape = []](
    **kwargs: Any,
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def kaiming_normal[Shape: _Shape = []](
    **kwargs: Any,
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def kaiming_uniform[Shape: _Shape = []](
    **kwargs: Any,
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def lecun_normal[Shape: _Shape = []](
    **kwargs: Any,
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def lecun_uniform[Shape: _Shape = []](
    **kwargs: Any,
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def orthogonal[Shape: _Shape = []](
    scale: float = ..., column_axis: int = ..., dtype: Any = ...
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def delta_orthogonal[Shape: _Shape = []](
    scale: float = ..., column_axis: int = ..., dtype: Any = ...
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def variance_scaling[Shape: _Shape = []](
    scale: float = ...,
    mode: str = ...,
    distribution: str = ...,
    in_axis: int | tuple[int, ...] = ...,
    out_axis: int | tuple[int, ...] = ...,
    batch_axis: tuple[int, ...] = ...,
    dtype: Any = ...,
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def xavier_normal[Shape: _Shape = []](
    **kwargs: Any,
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
def xavier_uniform[Shape: _Shape = []](
    **kwargs: Any,
) -> Callable[[Any, Shape, Any], _Array[Shape]]: ...
