/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#![cfg(test)]

mod abstract_methods;
mod annotation;
mod assign;
mod assign_any;
mod attribute_narrow;
mod attributes;
mod attrs;
mod callable;
mod calls;
mod cinderx;
mod class_keywords;
mod class_overrides;
mod class_subtyping;
mod class_super;
mod constructors;
mod contextual;
mod cycles;
mod dataclass_transform;
mod dataclasses;
mod decorators;
mod delayed_inference;
mod descriptors;
mod dict;
mod django;
mod enums;
mod explicit_any;
mod factory_boy;
mod flow_branching;
mod flow_looping;
mod functools;
mod generic_basic;
mod generic_callable_degeneracy;
mod generic_legacy;
mod generic_restrictions;
mod generic_sub;
mod higher_order;
mod imports;
mod incremental;
mod index_shape;
mod inference;
mod literal;
mod lsp;
mod map_int_tuples;
mod map_int_tuples_binding;
mod map_int_tuples_evaluation;
mod marshmallow;
mod mro;
mod named_tuple;
mod narrow;
mod natural;
mod new_type;
mod nn_module;
mod operators;
mod overload;
mod pandas;
mod paramspec;
mod pattern_match;
mod perf;
mod polars;
mod protocol;
mod pydantic;
mod pysa;
pub(crate) mod python_env;
mod pytorch_efficiency_lint;
mod query;
mod recursive_alias;
mod redundant_cast;
mod regular_nested_list;
mod returns;
mod scope;
mod self_cls_default;
mod semantic_syntax_errors;
mod sentinel;
mod shape_dsl;
mod shape_extension_restrictions;
mod simple;
mod sklearn;
mod slots;
mod state;
mod subscript_narrow;
mod suppression;
mod sys_info;
mod tsp;
mod tuple;
mod type_alias;
mod type_var_tuple;
mod type_variable_scope;
mod typed_dict;
mod typeform;
mod typing_self;
mod uninitialized_instance_variable;
mod unittest_mock_patch;
mod unnecessary_comparison;
mod unnecessary_type_conversion;
mod untyped_def_behaviors;
mod unused_call_result;
pub mod util;
mod var_resolution;
mod variance_inference;
mod with;
mod yields;
