name: Publish to PyPI

on:
  push:
    paths:
      - pyre2/version.bzl
    branches: [ pypi ]

jobs:
  push-tag:
    name: Push version tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get all history for all branches and tags
      - name: Get version
        run: echo "PYREFLY_VERSION=$(sed -n -e 's/^VERSION = "\(.*\)"/\1/p' pyre2/version.bzl)" >> $GITHUB_ENV
      - name: Tag commit
        run: git tag ${{ env.PYREFLY_VERSION }}
      - name: Push tag
        run: git push origin tag ${{ env.PYREFLY_VERSION }}
