name: Label Untriaged Issues

on:
  schedule:
    # Run once every weekday at midnight
    - cron: '0 0 * * 1-5'
  workflow_dispatch:  # Allow manual triggering

permissions:
  issues: write

jobs:
  label-untriaged:
    runs-on: ubuntu-latest
    steps:
      - name: Label untriaged issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get current date and calculate the date 48 hours ago
            const now = new Date();
            const twoDaysAgo = new Date(now);
            twoDaysAgo.setHours(now.getHours() - 48);
            const formattedDate = twoDaysAgo.toISOString().split('T')[0];

            console.log(`Finding untriaged issues created before ${formattedDate}...`);

            // Get 100 oldest issues without a Bug/Feature/Task type
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              type: 'none',
              per_page: 100,
              sort: 'created',
              direction: 'asc'
            });

            // Select issues that:
            // 1. Do not have the 'question' label
            // 2. Were created before the cutoff date
            // 3. Are not pull requests
            const oldIssues = issues.filter(issue => {
              const createdAt = new Date(issue.created_at);
              return !issue.labels.includes('question') &&
                     createdAt < twoDaysAgo &&
                     !issue.pull_request;
            });

            console.log(`Found ${oldIssues.length} old untriaged issues`);

            // Add 'needs-triage' label to each issue
            for (const issue of oldIssues) {
              console.log(`Adding 'needs-triage' label to issue #${issue.number}: ${issue.title}`);

              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['needs-triage']
              });
            }

            console.log('Finished labeling untriaged issues');
