# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING or hasattr(np, "complex256"):
    from numpy import complex256  # noqa: F401
if TYPE_CHECKING or hasattr(np, "float128"):
    from numpy import float128  # noqa: F401

from numpy import (  # noqa: F401
    __array_namespace_info__,
    all,
    allclose,
    amax,
    amin,
    angle,
    any,
    append,
    apply_along_axis,
    apply_over_axes,
    argmax,
    argpartition,
    argsort,
    argwhere,
    around,
    array,
    array2string,
    array_equal,
    array_equiv,
    array_repr,
    array_split,
    array_str,
    asanyarray,
    asarray,
    asarray_chkfinite,
    ascontiguousarray,
    asfortranarray,
    asmatrix,
    astype,
    atleast_1d,
    atleast_2d,
    atleast_3d,
    average,
    bartlett,
    base_repr,
    binary_repr,
    bincount,
    blackman,
    block,
    bmat,
    broadcast_arrays,
    broadcast_shapes,
    broadcast_to,
    busday_count,
    busday_offset,
    busdaycalendar,
    c_,
    can_cast,
    char,
    choose,
    column_stack,
    common_type,
    compress,
    concatenate,
    convolve,
    copy,
    copyto,
    core,
    corrcoef,
    correlate,
    count_nonzero,
    cov,
    cross,
    ctypeslib,
    cumprod,
    cumsum,
    cumulative_prod,
    cumulative_sum,
    datetime_as_string,
    datetime_data,
    delete,
    diag_indices,
    diag_indices_from,
    diagflat,
    diagonal,
    diff,
    digitize,
    dot,
    dsplit,
    dstack,
    dtypes,
    ediff1d,
    einsum,
    einsum_path,
    emath,
    empty_like,
    errstate,
    exceptions,
    extract,
    f2py,
    fft,
    finfo,
    fix,
    flatiter,
    flatnonzero,
    flip,
    fliplr,
    flipud,
    format_float_positional,
    format_float_scientific,
    frombuffer,
    fromfile,
    fromfunction,
    fromiter,
    frompyfunc,
    fromregex,
    fromstring,
    full_like,
    genfromtxt,
    geomspace,
    get_include,
    get_printoptions,
    getbufsize,
    geterr,
    geterrcall,
    gradient,
    hamming,
    hanning,
    histogram,
    histogram2d,
    histogram_bin_edges,
    histogramdd,
    hsplit,
    hstack,
    i0,
    iinfo,
    imag,
    index_exp,
    indices,
    info,
    inner,
    insert,
    interp,
    intersect1d,
    is_busday,
    isclose,
    iscomplex,
    iscomplexobj,
    isdtype,
    isfortran,
    isin,
    isneginf,
    isposinf,
    isreal,
    isrealobj,
    isscalar,
    issubdtype,
    iterable,
    ix_,
    kaiser,
    kron,
    lexsort,
    lib,
    linspace,
    load,
    loadtxt,
    logspace,
    ma,
    mask_indices,
    matrix,
    matrix_transpose,
    may_share_memory,
    median,
    memmap,
    meshgrid,
    mgrid,
    min_scalar_type,
    mintypecode,
    moveaxis,
    nan_to_num,
    nanargmax,
    nanargmin,
    nancumprod,
    nancumsum,
    nanmax,
    nanmean,
    nanmedian,
    nanmin,
    nanpercentile,
    nanprod,
    nanquantile,
    nanstd,
    nansum,
    nanvar,
    ndenumerate,
    ndim,
    ndindex,
    nditer,
    nested_iters,
    nonzero,
    ogrid,
    ones_like,
    outer,
    packbits,
    pad,
    partition,
    percentile,
    piecewise,
    place,
    poly,
    poly1d,
    polyadd,
    polyder,
    polydiv,
    polyfit,
    polyint,
    polymul,
    polynomial,
    polysub,
    polyval,
    printoptions,
    prod,
    promote_types,
    ptp,
    put,
    put_along_axis,
    putmask,
    quantile,
    r_,
    ravel,
    ravel_multi_index,
    real,
    real_if_close,
    rec,
    recarray,
    record,
    repeat,
    require,
    reshape,
    resize,
    result_type,
    roll,
    rollaxis,
    roots,
    rot90,
    s_,
    save,
    savetxt,
    savez,
    savez_compressed,
    ScalarType,
    sctypeDict,
    searchsorted,
    select,
    set_printoptions,
    setbufsize,
    setdiff1d,
    seterr,
    seterrcall,
    setxor1d,
    shape,
    shares_memory,
    show_config,
    show_runtime,
    sinc,
    size,
    sort,
    sort_complex,
    split,
    squeeze,
    stack,
    std,
    strings,
    swapaxes,
    take,
    take_along_axis,
    tensordot,
    testing,
    tile,
    trace,
    transpose,
    trapezoid,
    tri,
    tril,
    tril_indices,
    tril_indices_from,
    trim_zeros,
    triu,
    triu_indices,
    triu_indices_from,
    typecodes,
    typename,
    typing,
    union1d,
    unique,
    unique_all,
    unique_counts,
    unique_inverse,
    unique_values,
    unpackbits,
    unravel_index,
    unstack,
    unwrap,
    vander,
    var,
    vdot,
    vectorize,
    vsplit,
    vstack,
    where,
    zeros_like,
)
from numpy.linalg import (  # noqa: F401, F811
    cholesky,
    cond,
    cross,
    det,
    diagonal,
    eig,
    eigvals,
    eigvalsh,
    inv,
    lstsq,
    matmul,
    matrix_norm,
    matrix_power,
    matrix_rank,
    matrix_transpose,
    multi_dot,
    outer,
    pinv,
    qr,
    slogdet,
    svdvals,
    tensordot,
    tensorinv,
    tensorsolve,
    trace,
    vecdot,
    vector_norm,
)
from numpy.random import (  # noqa: F401
    beta,
    binomial,
    BitGenerator,
    bytes,
    chisquare,
    choice,
    default_rng,
    dirichlet,
    exponential,
    f,
    gamma,
    Generator,
    geometric,
    get_state,
    gumbel,
    hypergeometric,
    laplace,
    logistic,
    lognormal,
    logseries,
    MT19937,
    multinomial,
    multivariate_normal,
    negative_binomial,
    noncentral_chisquare,
    noncentral_f,
    normal,
    pareto,
    PCG64,
    PCG64DXSM,
    permutation,
    Philox,
    poisson,
    power,
    rand,
    randint,
    random,
    random_integers,
    random_sample,
    RandomState,
    ranf,
    rayleigh,
    sample,
    seed,
    SeedSequence,
    set_state,
    SFC64,
    shuffle,
    standard_cauchy,
    standard_exponential,
    standard_gamma,
    standard_normal,
    standard_t,
    triangular,
    uniform,
    vonmises,
    wald,
    weibull,
    zipf,
)
from shape_extensions import assert_shape


def test_reexports_available() -> None:
    scalar: np.int8 = np.int8(1)
    scalar_dtype: np.dtype[np.int8] = np.dtype(np.int8)

    assert isinstance(scalar, np.int8)
    assert scalar_dtype == np.dtype(np.int8)
    assert_shape(np.zeros(1).shape, (1,))
    assert not np.False_
    assert np.True_
    assert isinstance(np.__version__, str)
    assert np.e > 2.0
    assert np.euler_gamma > 0.0
    assert np.inf > 0.0
    assert isinstance(np.little_endian, bool)
    assert np.isnan(np.nan)
    assert np.newaxis is None
    assert np.pi > 3.0
    assert_shape(np.permute_dims(np.zeros((2, 3)), (0, 1)).shape, (2, 3))

    # These checks cover runtime behavior that the stubs do not model precisely.
    assert np.permute_dims(np.zeros((2, 3)), (1, 0)).shape == (3, 2)
    assert np.concat((np.zeros(1), np.zeros(1))).shape == (2,)
    assert np.concat((np.zeros(1), np.zeros(1)), axis=0).shape == (2,)

    if TYPE_CHECKING:
        np.concat((np.zeros(1), np.zeros(1)), axis="invalid")  # E: Argument
    assert np.from_dlpack(np.zeros(1)).shape == (1,)
    assert callable(np.test)
    assert issubclass(np.linalg.LinAlgError, ValueError)
